TefpsTvClient
Polyconseil/tefps-clients pull request #1
Opened 2017-10-18 16:25 UTC by odairay

2017-10-19 08:54 UTC, michau-k commented on src/main/java/fr/polyconseil/smartcity/tefpsclient/auth/OAuth2HttpClient.java
> +    private Oauth2ResponseDTO oauth2TokenClientCredentials() throws IOException {
Est-ce qu'on devrait pas utiliser le refresh token ici s'il y en a un?

2017-10-19 08:54 UTC, michau-k commented on src/main/java/fr/polyconseil/smartcity/tefpsclient/auth/OAuth2HttpClient.java
> +        if (currentAccessToken != null) {
soit null soit expiré du coup non?

2017-10-19 08:54 UTC, michau-k commented on src/main/java/fr/polyconseil/smartcity/tefpsclient/tv/TefpsTvClient.java
> +    public ParkingRightDTO createTv(
Est ce qu'on veut vraiment passer tous les paramètres à la main et pas simplement prendre le DTO en entrée?

2017-10-19 12:13 UTC, odairay commented on src/main/java/fr/polyconseil/smartcity/tefpsclient/auth/OAuth2HttpClient.java
> +    private Oauth2ResponseDTO oauth2TokenClientCredentials() throws IOException {
Bonne question, je me suis inspiré de ce qui était fait sur cvfm et le refresh token n'est pas utilisé, on refait une authentification quand l'access tokent expire

2017-10-19 12:13 UTC, odairay commented on src/main/java/fr/polyconseil/smartcity/tefpsclient/tv/TefpsTvClient.java
> +    public ParkingRightDTO createTv(
Yes c'est voulu de passer toutes les paramètres, pour que l'usage soit le plus simple possible pour parknow

2017-10-19 14:43 UTC, michau-k submitted a review, later dismissed

2017-10-23 14:46 UTC, Fitz3012 commented on java7/src/main/java/fr/polyconseil/smartcity/tefpsclients/auth/OAuth2HttpClient.java
> +            currentAccessTokenExpiration.setTime(currentAccessTokenExpiration.getTime() + oauth2Response.getExpiresIn() * 1000);
je pense que tu peux passer dans le constructeur directement

2017-10-23 14:46 UTC, Fitz3012 commented on java7/src/main/java/fr/polyconseil/smartcity/tefpsclients/tv/TefpsTvClient.java
> +        return tvUrl + "/" + TV_API + "/" + tvId;
tu peux utiliser les uribuilder ici non ?

2017-10-23 16:16 UTC, odairay commented
@Fitz3012 fixed mais pas complètement convaincu

2017-10-23 20:26 UTC, HenriJ requested changes
Surtout des points mineurs

2017-10-23 20:26 UTC, HenriJ commented on java7/src/main/java/fr/polyconseil/smartcity/tefpsclients/auth/dto/Oauth2RequestDTO.java
> +public class Oauth2RequestDTO {
J'ai pas vraiment l'impression que tu l'utilises celui là ?

2017-10-23 20:26 UTC, HenriJ commented on java7/src/main/java/fr/polyconseil/smartcity/tefpsclients/auth/OAuth2HttpClient.java
> +        ObjectMapper mapper = new ObjectMapper();
Évite de recréer un mapper à chaque fois (c'est coûteux). Créé en un dans le constructeur et utilise le ensuite (la sérialisation est thread-safe)

2017-10-23 20:26 UTC, HenriJ commented on java7/src/main/java/fr/polyconseil/smartcity/tefpsclients/auth/OAuth2HttpClient.java
> +        putRequest.setEntity(new StringEntity(mapper.writeValueAsString(entity)));
Micro-optim : `new ByteArrayEntity(mapper.writeValueAsBytes());` (dans tous les cas la String sera convertie en byte[] à un moment, donc autant sérialiser en byte[] tout de suite)

2017-10-23 20:26 UTC, HenriJ commented on java7/src/main/java/fr/polyconseil/smartcity/tefpsclients/auth/OAuth2HttpClient.java
> +    private HttpClient httpClient;
final ?

2017-10-23 20:26 UTC, HenriJ commented on java7/src/main/java/fr/polyconseil/smartcity/tefpsclients/auth/OAuth2HttpClient.java
> +        br.close();
Autant utiliser Apache Commons IO pour éviter de réinventer la roue :)
```
byte[] content = IOUtils.toByteArray(response.getEntity().getContent());
mapper.readValue(content, XXX.class);
```

2017-10-23 20:26 UTC, HenriJ commented on java7/src/main/java/fr/polyconseil/smartcity/tefpsclients/auth/dto/Oauth2RequestDTO.java
> +    public static final String GRANT_REFRESH_TOKEN = "refresh_token";
Je confirme que tu peux supprimer tout ce qui à trait au refresh_token qui n'a pas de sens dans le cadre d'une authentification client_crendetials (SI à SI). Ça n'a du sens que pour une authent d'un tiers (pour éviter de lui redemander son mot de passe à chaque fois)

2017-10-24 08:08 UTC, odairay commented
@Fitz3012 @HenriJ fixed

2017-10-24 09:28 UTC, merged